# Generated by Django 2.1.2 on 2018-12-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BattleWeb101', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_accuracy',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
