# Generated by Django 2.1.2 on 2018-12-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BattleWeb101', '0002_player_player_accuracy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attackedhistory',
            old_name='attacker_id',
            new_name='attacker',
        ),
        migrations.RenameField(
            model_name='attackedhistory',
            old_name='created_at',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='attackedhistory',
            old_name='victim_id',
            new_name='victim',
        ),
        migrations.AlterField(
            model_name='player',
            name='player_accuracy',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
        migrations.AlterUniqueTogether(
            name='attackedhistory',
            unique_together={('attacker', 'victim')},
        ),
    ]
