# Generated by Django 2.1.2 on 2018-12-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BattleWeb101', '0003_auto_20181214_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='attackedhistory',
            name='hit',
            field=models.BooleanField(default=False),
        ),
    ]
