# Generated by Django 2.1.2 on 2018-12-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BattleWeb101', '0004_attackedhistory_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='attackedhistory',
            name='grid_x_hit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='attackedhistory',
            name='grid_y_hit',
            field=models.IntegerField(null=True),
        ),
    ]
