# Generated by Django 2.1.2 on 2018-12-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BattleWeb101', '0005_auto_20181214_0718'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attackedhistory',
            unique_together=set(),
        ),
    ]
